/**
 * Component Registry System
 * Centralized management for all Amphibious components
 * Handles lifecycle, initialization, and cleanup
 * Part of Amphibious 2.0 Component Library
 */

/**
 * Constructor signature for any component that can be registered.
 * Components must accept an HTMLElement and an optional options object.
 */
type ComponentConstructor = new (
  element: HTMLElement,
  options?: Record<string, unknown>,
) => unknown;

/**
 * Lifecycle hook event names.
 */
type HookEvent = 'beforeInit' | 'afterInit' | 'beforeDestroy' | 'afterDestroy';

/**
 * Log severity levels.
 */
type LogLevel = 'info' | 'warn' | 'error';

/**
 * Configuration for a registered component type.
 *
 * @property selector - CSS selector used to auto-discover elements. Defaults to `[data-{type}]`.
 * @property autoInit - Whether to auto-initialize on DOM ready. Defaults to `true`.
 * @property singleton - Whether only one instance of this type is allowed. Defaults to `false`.
 */
export interface ComponentTypeConfig {
  selector: string;
  autoInit: boolean;
  singleton: boolean;
  [key: string]: unknown;
}

/**
 * Internal entry stored in the component type registry.
 */
interface ComponentTypeEntry {
  constructor: ComponentConstructor;
  config: ComponentTypeConfig;
}

/**
 * Reference to a live component instance stored in the registry.
 *
 * @property id - Unique identifier generated by the registry.
 * @property type - The registered component type name.
 * @property element - The DOM element the component is bound to.
 * @property instance - The instantiated component object.
 * @property options - Merged options (data attributes + programmatic).
 * @property created - Timestamp (ms since epoch) when the component was created.
 */
export interface ComponentRef {
  id: string;
  type: string;
  element: HTMLElement;
  instance: unknown;
  options: Record<string, unknown>;
  created: number;
}

/**
 * Global registry configuration.
 *
 * @property autoInit - Automatically initialize components on DOM ready. Defaults to `true`.
 * @property debug - Enable debug logging. Defaults to `false`.
 * @property namespace - Prefix for generated component IDs. Defaults to `'amphibious'`.
 * @property initAttribute - Data attribute used for component discovery. Defaults to `'data-component'`.
 * @property lazyLoad - Defer initialization until elements enter the viewport. Defaults to `false`.
 */
export interface RegistryConfig {
  autoInit: boolean;
  debug: boolean;
  namespace: string;
  initAttribute: string;
  lazyLoad: boolean;
}

/**
 * Lifecycle hooks map. Each event holds an array of callbacks.
 */
interface LifecycleHooks {
  beforeInit: Array<(data: HookData) => void>;
  afterInit: Array<(data: ComponentRef) => void>;
  beforeDestroy: Array<(data: ComponentRef) => void>;
  afterDestroy: Array<(data: ComponentRef) => void>;
}

/**
 * Data passed to `beforeInit` hooks.
 */
interface HookData {
  type: string;
  element: HTMLElement;
  options: Record<string, unknown>;
}

/**
 * Performance metrics tracked by the registry.
 */
export interface RegistryMetrics {
  initialized: number;
  destroyed: number;
  errors: number;
  initTime: number;
  active?: number;
  types?: number;
}

/**
 * Serialized component information returned by {@link ComponentRegistry.listComponents}.
 */
interface ComponentListEntry {
  id: string;
  type: string;
  element: HTMLElement;
  created: string;
}

/**
 * Built-in component descriptor used during registration.
 */
interface BuiltInComponent {
  type: string;
  ComponentClass: ComponentConstructor | undefined;
}

/**
 * Centralized registry for all Amphibious components.
 *
 * Manages component lifecycle (creation, initialization, destruction),
 * auto-discovers components via data attributes, observes the DOM for
 * dynamically added/removed elements, and exposes lifecycle hooks.
 *
 * @example
 * ```ts
 * const registry = new ComponentRegistry();
 * registry.registerComponent('tooltip', TooltipClass, { selector: '[data-tooltip]' });
 * registry.initializeAll();
 * ```
 */
export class ComponentRegistry {
  /** Map of component instances keyed by unique ID. */
  private components: Map<string, ComponentRef>;

  /** Map of component constructors keyed by type name. */
  private componentTypes: Map<string, ComponentTypeEntry>;

  /** Global configuration. */
  private config: RegistryConfig;

  /** Lifecycle hook callbacks. */
  private hooks: LifecycleHooks;

  /** Performance metrics. */
  private metrics: RegistryMetrics;

  /** MutationObserver for dynamic content detection. */
  private observer: MutationObserver | null;

  constructor() {
    this.components = new Map();
    this.componentTypes = new Map();

    this.config = {
      autoInit: true,
      debug: false,
      namespace: 'amphibious',
      initAttribute: 'data-component',
      lazyLoad: false,
    };

    this.hooks = {
      beforeInit: [],
      afterInit: [],
      beforeDestroy: [],
      afterDestroy: [],
    };

    this.metrics = {
      initialized: 0,
      destroyed: 0,
      errors: 0,
      initTime: 0,
    };

    this.observer = null;

    // Initialize on DOM ready
    this.init();
  }

  /**
   * Initialize the registry by waiting for DOM readiness.
   */
  private init(): void {
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', () => this.setup());
    } else {
      this.setup();
    }
  }

  /**
   * Setup registry: register built-in components, auto-initialize,
   * start the mutation observer, and attach the unload handler.
   */
  private setup(): void {
    this.registerBuiltInComponents();

    if (this.config.autoInit) {
      this.initializeAll();
    }

    this.setupObserver();

    window.addEventListener('beforeunload', () => this.destroyAll());
  }

  /**
   * Register all built-in Amphibious components from the global window scope.
   */
  private registerBuiltInComponents(): void {
    // biome-ignore lint/suspicious/noExplicitAny: window globals are untyped component constructors
    const win = window as any;

    const components: BuiltInComponent[] = [
      { type: 'accordion', ComponentClass: win.Accordion },
      { type: 'aiab-datepicker', ComponentClass: win.DatePicker },
      { type: 'dropdown', ComponentClass: win.Dropdown },
      { type: 'file-upload', ComponentClass: win.FileUpload },
      { type: 'modal', ComponentClass: win.ModalComponent },
      { type: 'navigation', ComponentClass: win.NavigationComponent },
      { type: 'aiab-search-bar', ComponentClass: win.SearchBar },
      { type: 'toast', ComponentClass: win.ToastComponent },
      { type: 'aiab-data-table', ComponentClass: win.DataTableComponent },
    ];

    for (const { type, ComponentClass } of components) {
      if (ComponentClass) {
        this.registerComponent(type, ComponentClass);
      }
    }
  }

  /**
   * Register a component type with the registry.
   *
   * @param type - Unique name for this component type (e.g. `'modal'`, `'tooltip'`).
   * @param ComponentClass - Constructor that creates component instances.
   * @param config - Optional configuration overrides for auto-init, selector, etc.
   */
  public registerComponent(
    type: string,
    ComponentClass: ComponentConstructor,
    config: Partial<ComponentTypeConfig> = {},
  ): void {
    if (this.componentTypes.has(type)) {
      this.log(`Component type "${type}" already registered`, 'warn');
      return;
    }

    this.componentTypes.set(type, {
      constructor: ComponentClass,
      config: {
        selector: config.selector || `[data-${type}]`,
        autoInit: config.autoInit !== false,
        singleton: config.singleton || false,
        ...config,
      },
    });

    this.log(`Registered component type: ${type}`);
  }

  /**
   * Initialize all registered component types within a DOM subtree.
   *
   * @param root - Root element or document to scan for components. Defaults to `document`.
   */
  public initializeAll(root: Document | HTMLElement = document): void {
    const startTime = performance.now();

    this.componentTypes.forEach((componentDef, type) => {
      if (componentDef.config.autoInit) {
        const elements = root.querySelectorAll<HTMLElement>(componentDef.config.selector);
        elements.forEach((element) => {
          this.createComponent(type, element);
        });
      }
    });

    this.metrics.initTime = performance.now() - startTime;
    this.log(`Initialized all components in ${this.metrics.initTime.toFixed(2)}ms`);
  }

  /**
   * Create a single component instance and register it.
   *
   * @param type - The registered component type name.
   * @param element - The DOM element to bind the component to.
   * @param options - Programmatic options merged with data-attribute options.
   * @returns The created component instance, or `null` on failure.
   */
  public createComponent(
    type: string,
    element: HTMLElement,
    options: Record<string, unknown> = {},
  ): unknown | null {
    const componentDef = this.componentTypes.get(type);
    if (!componentDef) {
      this.log(`Unknown component type: ${type}`, 'error');
      this.metrics.errors++;
      return null;
    }

    const existingId = element.dataset.componentId;
    if (existingId && this.components.has(existingId)) {
      this.log(`Element already has component: ${existingId}`, 'warn');
      return this.components.get(existingId)?.instance ?? null;
    }

    const id = this.generateId(type);
    const dataOptions = this.parseDataAttributes(element, type);
    const mergedOptions: Record<string, unknown> = { ...dataOptions, ...options };

    try {
      this.runHooks('beforeInit', { type, element, options: mergedOptions });

      const instance = new componentDef.constructor(element, mergedOptions);

      const componentRef: ComponentRef = {
        id,
        type,
        element,
        instance,
        options: mergedOptions,
        created: Date.now(),
      };

      this.components.set(id, componentRef);
      element.dataset.componentId = id;

      this.runHooks('afterInit', componentRef);

      this.metrics.initialized++;
      this.log(`Created ${type} component: ${id}`);

      return instance;
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : String(error);
      this.log(`Failed to create ${type} component: ${message}`, 'error');
      this.metrics.errors++;
      return null;
    }
  }

  /**
   * Destroy a component instance by ID or element reference.
   *
   * @param idOrElement - Component ID string or the HTMLElement bound to the component.
   * @returns `true` if the component was successfully destroyed, `false` otherwise.
   */
  public destroyComponent(idOrElement: string | HTMLElement): boolean {
    const id = typeof idOrElement === 'string' ? idOrElement : idOrElement.dataset?.componentId;

    if (!id || !this.components.has(id)) {
      this.log(`Component not found: ${id}`, 'warn');
      return false;
    }

    const componentRef = this.components.get(id) as ComponentRef;

    try {
      this.runHooks('beforeDestroy', componentRef);

      // biome-ignore lint/suspicious/noExplicitAny: component instances have varying shapes; destroy() presence is checked at runtime
      const instance = componentRef.instance as any;
      if (typeof instance.destroy === 'function') {
        instance.destroy();
      }

      delete componentRef.element.dataset.componentId;

      this.components.delete(id);

      this.runHooks('afterDestroy', componentRef);

      this.metrics.destroyed++;
      this.log(`Destroyed ${componentRef.type} component: ${id}`);

      return true;
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : String(error);
      this.log(`Failed to destroy component ${id}: ${message}`, 'error');
      this.metrics.errors++;
      return false;
    }
  }

  /**
   * Destroy all registered component instances.
   */
  public destroyAll(): void {
    const ids = Array.from(this.components.keys());
    for (const id of ids) {
      this.destroyComponent(id);
    }
    this.log(`Destroyed all ${ids.length} components`);
  }

  /**
   * Get a component instance by ID or element reference.
   *
   * @param idOrElement - Component ID string or the HTMLElement bound to the component.
   * @returns The component instance, or `null` if not found.
   */
  public getComponent(idOrElement: string | HTMLElement): unknown | null {
    if (typeof idOrElement === 'string') {
      return this.components.get(idOrElement)?.instance ?? null;
    }

    const id = idOrElement.dataset?.componentId;
    return id ? (this.components.get(id)?.instance ?? null) : null;
  }

  /**
   * Get all component instances of a specific type.
   *
   * @param type - The registered component type name.
   * @returns Array of component instances matching the given type.
   */
  public getComponentsByType(type: string): unknown[] {
    const result: unknown[] = [];
    this.components.forEach((ref) => {
      if (ref.type === type) {
        result.push(ref.instance);
      }
    });
    return result;
  }

  /**
   * Setup a MutationObserver to auto-initialize components on dynamically
   * added nodes and auto-destroy components on removed nodes.
   */
  private setupObserver(): void {
    if (!window.MutationObserver || !this.config.autoInit) return;

    this.observer = new MutationObserver((mutations: MutationRecord[]) => {
      for (const mutation of mutations) {
        // Handle added nodes
        mutation.addedNodes.forEach((node) => {
          if (node.nodeType === Node.ELEMENT_NODE) {
            this.initializeAll(node as HTMLElement);
          }
        });

        // Handle removed nodes
        mutation.removedNodes.forEach((node) => {
          if (node.nodeType === Node.ELEMENT_NODE) {
            const el = node as HTMLElement;
            const components = el.querySelectorAll<HTMLElement>('[data-component-id]');
            components.forEach((element) => {
              this.destroyComponent(element);
            });
          }
        });
      }
    });

    this.observer.observe(document.body, {
      childList: true,
      subtree: true,
    });
  }

  /**
   * Parse data attributes on an element into a component options object.
   * Attributes matching `data-{type}-*` are extracted, camelCased, and
   * coerced to JSON, boolean, or number values when possible.
   *
   * @param element - The DOM element to read attributes from.
   * @param type - The component type name (used as the attribute prefix).
   * @returns Parsed options object.
   */
  private parseDataAttributes(element: HTMLElement, type: string): Record<string, unknown> {
    const options: Record<string, unknown> = {};
    const prefix = `data-${type}-`;

    Array.from(element.attributes).forEach((attr: Attr) => {
      if (attr.name.startsWith(prefix)) {
        const key = attr.name
          .slice(prefix.length)
          .replace(/-([a-z])/g, (_: string, letter: string) => letter.toUpperCase());

        let value: unknown = attr.value;
        try {
          value = JSON.parse(attr.value);
        } catch {
          // Keep as string if not valid JSON, but coerce common types
          if (attr.value === 'true') value = true;
          else if (attr.value === 'false') value = false;
          else if (!Number.isNaN(Number(attr.value)) && attr.value !== '')
            value = Number(attr.value);
        }

        options[key] = value;
      }
    });

    return options;
  }

  /**
   * Add a lifecycle hook callback.
   *
   * @param event - The lifecycle event to hook into.
   * @param callback - Function called when the event fires.
   */
  public addHook(event: HookEvent, callback: (data: HookData | ComponentRef) => void): void {
    if (!this.hooks[event]) {
      this.log(`Unknown hook event: ${event}`, 'warn');
      return;
    }
    // biome-ignore lint/suspicious/noExplicitAny: hook arrays have differing callback signatures per event; runtime dispatch is safe
    (this.hooks[event] as any[]).push(callback);
  }

  /**
   * Run all callbacks for a lifecycle hook event.
   *
   * @param event - The lifecycle event name.
   * @param data - Data payload passed to each callback.
   */
  private runHooks(event: HookEvent, data: HookData | ComponentRef): void {
    if (!this.hooks[event]) return;

    // biome-ignore lint/suspicious/noExplicitAny: hooks map has heterogeneous callback signatures; unified iteration requires any
    const callbacks = this.hooks[event] as Array<(data: any) => void>;
    for (const callback of callbacks) {
      try {
        callback(data);
      } catch (error: unknown) {
        const message = error instanceof Error ? error.message : String(error);
        this.log(`Hook error in ${event}: ${message}`, 'error');
      }
    }
  }

  /**
   * Generate a unique component ID.
   *
   * @param type - The component type name, used as a prefix.
   * @returns A unique string ID.
   */
  private generateId(type: string): string {
    return `${this.config.namespace}-${type}-${Date.now()}-${Math.random().toString(36).substring(2, 11)}`;
  }

  /**
   * Merge new configuration into the registry's global config.
   *
   * @param config - Partial configuration to merge.
   */
  public configure(config: Partial<RegistryConfig>): void {
    this.config = { ...this.config, ...config };
  }

  /**
   * Get current registry performance metrics.
   *
   * @returns Metrics including active component count and registered type count.
   */
  public getMetrics(): RegistryMetrics {
    return {
      ...this.metrics,
      active: this.components.size,
      types: this.componentTypes.size,
    };
  }

  /**
   * List all active components for debugging purposes.
   *
   * @returns Array of serialized component entries.
   */
  public listComponents(): ComponentListEntry[] {
    const list: ComponentListEntry[] = [];
    this.components.forEach((ref, id) => {
      list.push({
        id,
        type: ref.type,
        element: ref.element,
        created: new Date(ref.created).toISOString(),
      });
    });
    return list;
  }

  /**
   * Logging helper. Output is suppressed unless `config.debug` is `true`.
   *
   * @param _message - Log message (prefixed with `[Amphibious Registry]` internally).
   * @param level - Severity level. Defaults to `'info'`.
   */
  private log(_message: string, level: LogLevel = 'info'): void {
    if (!this.config.debug) return;

    const _prefix = '[Amphibious Registry]';

    switch (level) {
      case 'error':
        // Error logging disabled for production
        break;
      case 'warn':
        // Warning logging disabled for production
        break;
      default:
        // Info logging disabled for production
        break;
    }
  }

  /**
   * Fully tear down the registry: destroy all components, disconnect the
   * mutation observer, and clear all internal maps and hooks.
   */
  public destroy(): void {
    this.destroyAll();

    if (this.observer) {
      this.observer.disconnect();
      this.observer = null;
    }

    this.components.clear();
    this.componentTypes.clear();
    this.hooks = {
      beforeInit: [],
      afterInit: [],
      beforeDestroy: [],
      afterDestroy: [],
    };
  }
}

declare global {
  interface Window {
    AmphibiousRegistry?: ComponentRegistry;
  }
}

// Create global registry instance
if (typeof window !== 'undefined') {
  window.AmphibiousRegistry = new ComponentRegistry();
}

// Export for module usage
export default ComponentRegistry;
export { ComponentRegistry as ComponentRegistryClass };
